language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.4
  - DJANGO=1.4.1
install:
  - pip install Django==$DJANGO
  - python setup.py install
script: python setup.py test
notifications:
  email:
    recipients:
      - swistakm@gmail.com
    on_success: always
    on_failure: always